mqtt:
  sensor:
    - name: "temperature"
      icon: "mdi:thermometer"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "°F"
      value_template: "{{ value_json.temperature }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "humidity"
      icon: "mdi:water-percent"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "pm1.0"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm1 }}"
      json_attributes_topic: "home/rpi/1/status"