mqtt:
  sensor:
    - name: "temperature"
      icon: "mdi:thermometer"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "°F"
      value_template: "{{ value_json.temperature }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "humidity"
      icon: "mdi:water-percent"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "co2_concentration"
      icon: "mdi:cloud"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "ppm"
      value_template: "{{ value_json.co2_concentration }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "co2_abc"
      icon: "mdi:cloud"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "ppm"
      value_template: "{{ value_json.co2_abc }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "pm1.0"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm1 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "pm2.5"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm2.5 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "pm4.0"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm4 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "pm10"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm10 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "nc0.5"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc0.5 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "nc1"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc1 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "nc2.5"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc2.5 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "nc4"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc4 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "nc10"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc10 }}"
      json_attributes_topic: "home/rpi/1/status"

    - name: "typical_particle"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µm"
      value_template: "{{ value_json.typical_particle }}"
      json_attributes_topic: "home/rpi/1/status"

