mqtt:
  sensor:
    - name: "mqtt_rpi1_temperature"
      icon: "mdi:thermometer"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "°F"
      value_template: "{{ value_json.temperature }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "bc8171ae-1ccc-4e39-b5cd-9965e1219398"

    - name: "mqtt_rpi1_humidity"
      icon: "mdi:water-percent"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "%"
      value_template: "{{ value_json.humidity }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "e3db2b8e-2c48-4209-9b7b-fd308e6956c3"

    - name: "mqtt_rpi1_co2_concentration"
      icon: "mdi:cloud"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "ppm"
      value_template: "{{ value_json.co2_concentration }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "06cf4bcd-7f86-498a-8a75-dec5e6812bf8"

    - name: "mqtt_rpi1_co2_abc"
      icon: "mdi:cloud"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "ppm"
      value_template: "{{ value_json.co2_abc }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "b29f7bbf-55d0-4bfb-8a00-9f071d742bdd"

    - name: "mqtt_rpi1_pm1.0"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm1 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "d2e4171c-73ac-4a25-9c4c-9af83ebfe2e3"

    - name: "mqtt_rpi1_pm2.5"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm2.5 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "76df1f5b-ba5d-45ac-be11-1f83e738a8d7"

    - name: "mqtt_rpi1_pm4.0"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm4 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "6a7c0e6d-4b66-4cde-a078-a52429cf6f3d"

    - name: "mqtt_rpi1_pm10"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µg/m³"
      value_template: "{{ value_json.pm10 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "4aeebb0c-9b97-4351-920b-e7b805368917"

    - name: "mqtt_rpi1_nc0.5"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc0.5 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "90bebbf5-8643-4ca1-9d52-d4d0d003efcc"

    - name: "mqtt_rpi1_nc1"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc1 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "1e9487f4-f422-4a90-a461-0af8b07ac6ff"

    - name: "mqtt_rpi1_nc2.5"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc2.5 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "1e8a016a-f018-4f90-b609-f51a1e966675"

    - name: "mqtt_rpi1_nc4"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc4 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "2b31bf11-9e34-4b1c-9b83-137b98ae9401"

    - name: "mqtt_rpi1_nc10"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "particles/cm³"
      value_template: "{{ value_json.nc10 }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "23af1d7e-e086-45d9-9a66-ae5a2e04dbe0"

    - name: "mqtt_rpi1_typical_particle"
      icon: "mdi:blur"
      state_topic: "home/rpi/1/status"
      unit_of_measurement: "µm"
      value_template: "{{ value_json.typical_particle }}"
      json_attributes_topic: "home/rpi/1/status"
      unique_id: "5853fde3-80ac-48b3-a387-ce51fa01eef7"

