apiVersion: 1

datasources:
- name: InfluxDB
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  user: user
  password: pass
  database: my-bucket
  isDefault: true
  editable: true
  jsonData:
    version: Flux
    org: myorg
  secureJsonData:
    token: 0b982Cxo-o7wbDsxMLTqxoRvHAQ_P1yA5NgjV53usDeg0ZgMj4DfKu0JCEFyRvK1PnepIBfys1U1v6npjctSMQ==
